In [2]:
# import mumpy
import numpy as np

In [4]:
#create numpy arrays
arr = np.array([10,20,30])
print(arr)

[10 20 30]


In [10]:
#Array properties helps you understand and manipulate data in arrays efficiently.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Dimensions - (4 x 3) 
print("shape of array is :",arr.shape)

# Total elements - (12) 
print("total elements is :" , arr.size)

# Number of dimensions - 2
print("print ndim is :",arr.ndim)

# Data type object - int64
print(arr.dtype)

# Size of each element in bytes - 8 for int64
print(arr.itemsize)

shape of array is : (4, 3)
total elements is : 12
print ndim is : 2
int64
8


In [11]:
#Mathematical operations
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [12]:
#Vectorization:Operations on entire arrays without explicit loops, making code cleaner and faster

#Normal Python:
numbers = [10, 20, 30, 40]

result = []

for number in numbers:
    result.append(number * 2)

print(result)


#NumPy mein:
numbers = np.array([10, 20, 30, 40])

result = numbers * 2

print(result)

[20, 40, 60, 80]
[20 40 60 80]


In [35]:
# Creating NumPy Arrays - from scratch 

# 3x4 array of 0s 
arr1 = np.zeros((3, 4))
print(arr1, arr1.shape)

# 3x4 array of 1s 
arr2 = np.ones((3,4))
print(arr2, arr2.shape)

# 3x4 array of 5s 
arr3 = np.full((3,4),5)
print(arr3, arr3.shape)

# Identity matrix of 3x3
arr4 = np.eye(3)
print(arr4, arr4.shape)

# Elements in range(1, 20) in step of 1s
arr5 = np.arange(1, 20, 1) 
print(arr5, arr5.shape) 

# Evenly spaced array
arr6 = np.linspace(0, 100, 11) 
print(arr6, arr6.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] (19,)
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.] (11,)


In [ ]:
#NumPy Built-in Functions

